### PR TITLE
Add endpoint to fetch user balances

### PR DESCRIPTION
**Pull request by gnardini**
Added an endpoint that will be used in this PR: https://github.com/valora-inc/wallet/pull/1386 to fetch the token balances for users.

### CODE REVIEW

**Review by silasbw — COMMENTED** [review]
probably a dumb question: do you know if blockscout is likely to support all the tokens Valora will?  do we care?

**Comment by gnardini** [comment]
Blockscout returns all tokens that implement the ERC20 interface, it does no filtering. It just indexes every token that exists and returns their balance, even if they are not listed on any exchange.

**Review by silasbw — APPROVED** [review]
:artist:

**Review by dievazqu — APPROVED** [review]
LGTM

**Pull request merged**
